name: Publish Dashboard to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abrarsaquib/saaschat-dashboard:latest
          # ADD THESE CACHE-BUSTING ARGUMENTS:
          build-args: |
            NODE_ENV=production
            # This will bust the cache on every build:
            CACHE_BUST=${{ github.run_id }}${{ github.run_attempt }}